version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "02:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pylint
    versions:
    - 2.6.0
    - 2.6.2
    - 2.7.0
    - 2.7.1
    - 2.7.2
    - 2.7.3
    - 2.7.4
    - 2.8.1
  - dependency-name: sqlalchemy
    versions:
    - 1.3.22
    - 1.3.23
    - 1.4.0
    - 1.4.1
    - 1.4.10
    - 1.4.2
    - 1.4.3
    - 1.4.4
    - 1.4.5
    - 1.4.6
    - 1.4.7
    - 1.4.8
    - 1.4.9
  - dependency-name: astroid
    versions:
    - "2.5"
    - 2.5.1
    - 2.5.2
    - 2.5.3
  - dependency-name: autopep8
    versions:
    - 1.5.4
    - 1.5.5
  - dependency-name: isort
    versions:
    - 5.7.0
  - dependency-name: typed-ast
    versions:
    - 1.4.2
  - dependency-name: lazy-object-proxy
    versions:
    - 1.5.2
